
desc "构建model输出"
task :install do
  sh 'cd .. && sudo make build'
end

task :buildmodel do
  sh 'python ../bin/chameleon test.model -d chameleonDemo/chameleonDemo'
end

task :test => [:install, :buildmodel]  do
  sh 'cd ./chameleonDemo && xctool -project chameleonDemo.xcodeproj -scheme chameleonDemoTests test'
end

task :request => [:install] do
  sh 'python ../bin/chameleon test.model --outType=bwmodel -d requestOutput'
end

task :default => :test
